name: GitHub-Metrics

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: metrics
    steps:
      - name: metrics_base
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          filename: metrics_base.svg
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          template: classic
          base: header, activity, community, repositories, metadata

      - name: metrics_languages
        uses: gh-metrics/metrics@latest
        continue-on-error: true
        with:
          filename: metrics_languages.svg
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 30

      - name: metrics_isocalendar
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          filename: metrics_isocalendar.svg
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: metrics_topics
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          filename: metrics_topics.svg
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          template: classic
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 15

      - name: metrics_topics
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          filename: metrics_topics_icons.svg
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          template: classic
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons

      - name: metrics_calendar
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          filename: metrics_calendar.svg
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          template: classic
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 3

      - name: metrics_sponsors
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          filename: metrics_sponsors.svg
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          template: classic
          base: ""
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, about, list
          plugin_sponsors_past: yes
